"""
SQLAlchemy ORM models for StratosHealth telemetry, caching, and advisory data.
"""

from datetime import datetime
from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    DateTime,
    Text,
    Boolean,
    JSON,
)
from database import Base


class FireEvent(Base):
    """
    Caches active wildfire events fetched from NASA EONET v3 or FIRMS satellites.
    Prevents API rate limiting and provides offline fallback for live demonstrations.
    """
    __tablename__ = "fire_events"

    id = Column(Integer, primary_key=True, index=True)
    eonet_id = Column(String(64), unique=True, index=True, nullable=False)
    title = Column(String(255), nullable=False)
    category = Column(String(64), default="Wildfires")
    latitude = Column(Float, nullable=False, index=True)
    longitude = Column(Float, nullable=False, index=True)
    event_date = Column(DateTime, nullable=False, index=True)
    source_name = Column(String(64), default="NASA EONET v3")
    source_url = Column(String(512), nullable=True)
    is_active = Column(Boolean, default=True)
    raw_properties = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self) -> str:
        return f"<FireEvent(eonet_id='{self.eonet_id}', title='{self.title}')>"


class AirQualityReading(Base):
    """
    Stores environmental telemetry stations replicating EPA AirNow readings
    across the Pacific Northwest (Bend, Redmond, Eugene, Cascade Ridge, etc.).
    """
    __tablename__ = "air_quality_readings"

    id = Column(Integer, primary_key=True, index=True)
    station_id = Column(String(32), unique=True, index=True, nullable=False)
    station_name = Column(String(128), nullable=False)
    sector = Column(String(64), default="Pacific NW - Sector 7B")
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    aqi = Column(Integer, nullable=False, index=True)
    pm2_5 = Column(Float, nullable=False)  # in µg/m³
    pm10 = Column(Float, nullable=False)   # in µg/m³
    no2 = Column(Float, nullable=True)     # in ppb (TEMPO correlation)
    ozone = Column(Float, nullable=True)   # in ppm
    temperature_f = Column(Float, nullable=True)
    humidity_pct = Column(Float, nullable=True)
    wind_speed_mph = Column(Float, nullable=True)
    wind_direction_deg = Column(Integer, nullable=True)
    dominant_pollutant = Column(String(32), default="PM2.5")
    health_status = Column(String(64), default="Unhealthy")
    recorded_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return f"<AirQualityReading(station='{self.station_name}', aqi={self.aqi})>"


class TacticalAdvisory(Base):
    """
    Stores AI-synthesized emergency advisories generated by fusing live fire
    spread, TEMPO NO2 plume dispersion, and EPA AirNow ground sensors.
    """
    __tablename__ = "tactical_advisories"

    id = Column(Integer, primary_key=True, index=True)
    sector = Column(String(64), default="Pacific NW - Sector 7B", index=True)
    urgency_level = Column(String(32), default="LEVEL 4 - CRITICAL", index=True)
    status = Column(String(64), default="ANALYSIS COMPLETE")
    headline = Column(String(255), nullable=False)
    advisory_text = Column(Text, nullable=False)
    evacuation_routes = Column(JSON, nullable=True)
    shelter_assignments = Column(JSON, nullable=True)
    at_risk_population = Column(Integer, default=38400)
    confidence_score = Column(Float, default=94.2)
    model_version = Column(String(64), default="HYSPLIT + TEMPO Fusion v3.1")
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self) -> str:
        return f"<TacticalAdvisory(sector='{self.sector}', urgency='{self.urgency_level}')>"
